### ISSUE TITLE
Cocos Creator Unity Ads for iOS 13

### ISSUE THREAD

**Issue by RaoNawaz** [lyzz0612/Cocos-Creator-Snippet#1]
Dear Cocos Creator Team , 
We are using Unity Ads version 2.5.0.5 with SDKBOX.  Our Unity ads are not appearing as full screen on iOS 13 devices. 
Can you please look into it and fix.

Thanks 
![unnamed](https://user-images.githubusercontent.com/3539304/69143645-4639b200-0aeb-11ea-8150-77b06896ab2d.jpg)

![Capture](https://user-images.githubusercontent.com/3539304/69143559-14c0e680-0aeb-11ea-94ea-c6e4e691ef71.PNG)
![IMG_20191111_144637__01](https://user-images.githubusercontent.com/3539304/69143616-3621d280-0aeb-11ea-9161-3a553f7a26e5.jpg)

**Comment by lyzz0612** [comment]
sorry, I'm not in Cocos Creator team. you may ask in [AnySdk](https://github.com/AnySDK/Sample_Unity).
